config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  
  resources :exchanges do
    member do
      get :exchanges_movimentation
    end

    collection do
      get :exchanges_list
    end
  end

  resources :investment_funds

 resources :stocks do 
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :wallets
  

  root :to => 'home#index'  #RAILS 3

end

app/models/investment_fund.rb
class InvestmentFund < ActiveRecord::Base
  belongs_to :wallet
  def gross_profit
    gross_income = self[:capital]*(years_of_investment*0.12)
  end

  def liquid_profit
    liquid_income = gross_profit - (gross_profit*ir_tax(days_of_investment) + gross_profit*(years_of_investment*(self[:admTax]/100)))
  end

  def years_of_investment
    (Date.today.year-self[:buyDate].year).to_i
  end

  def days_of_investment
    (Date.today.to_date-self[:buyDate]).to_i
  end
  
  def ir_tax(days)
    
    raise InvalidNumberOfDays if days < 0
    
    if(0 <= days && days <= 180)
    0.25
    elsif(181 <= days && days <= 361)
    0.20
    elsif(362 <= days && days <= 720)
    0.175
    elsif(days > 720)
    0.15
  end
  end
end

app/controllers/investment_funds_controller.rb
class InvestmentFundsController < ApplicationController
  before_action :set_investment_fund, only: [:show, :edit, :update, :destroy]

  # GET /investment_funds
  def index
    @investment_funds = InvestmentFund.all
  end

  # GET /investment_funds/1
  def show
  end

  # GET /investment_funds/new
  def new
    @investment_fund = InvestmentFund.new
  end

  # GET /investment_funds/1/edit
  def edit
  end

  # POST /investment_funds
  def create
    @investment_fund = InvestmentFund.new(investment_fund_params)

    if @investment_fund.save
      redirect_to @investment_fund, notice: 'Investment fund was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /investment_funds/1
  def update
    if @investment_fund.update(investment_fund_params)
      redirect_to @investment_fund, notice: 'Investment fund was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /investment_funds/1
  def destroy
    @investment_fund.destroy
    redirect_to investment_funds_url, notice: 'Investment fund was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment_fund
      @investment_fund = InvestmentFund.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def investment_fund_params
      params.require(:investment_fund).permit(:name, :buyDate, :admTax, :aditionalInfo, :exitTax, :fundBegin, :manager, :managerContact, :shareValue, :capital, :wallet_id, :closing_price, :closing_date)
    end
    
    
end

app/helpers/investment_funds_helper.rb
module InvestmentFundsHelper
end

app/views/investment_funds/_form.html.erb
<%= form_for(@investment_fund) do |f| %>
<% if @investment_fund.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@investment_fund.errors.count, "error") %> prohibited this investment_fund from being saved:</h2>

	<ul>
		<% @investment_fund.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div row>
	<div class="small-4 small-centered columns">
		<div class="field">
			<%= f.label :name %>
			<br>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :buyDate %>
			<br>
			<%= f.date_select :buyDate %>
		</div>
		<div class="field">
			<%= f.label :admTax %>
			<br>
			<%= f.number_field :admTax, :step => 0.01 %>
		</div>
		<div class="field">
			<%= f.label :aditionalInfo %>
			<br>
			<%= f.text_field :aditionalInfo %>
		</div>
		<div class="field">
			<%= f.label :exitTax %>
			<br>
			<%= f.number_field :exitTax, :step => 0.01 %>
		</div>
		<div class="field">
			<%= f.label :fundBegin %>
			<br>
			<%= f.date_select :fundBegin %>
		</div>
		<div class="field">
			<%= f.label :manager %>
			<br>
			<%= f.text_field :manager %>
		</div>
		<div class="field">
			<%= f.label :managerContact %>
			<br>
			<%= f.text_field :managerContact %>
		</div>
		<div class="field">
			<%= f.label :shareValue %>
			<br>
			<%= f.number_field :shareValue, :step => 0.01 %>
		</div>
		<div class="field">
			<%= f.label :capital %>
			<br>
			<%= f.number_field :capital, :step => 0.01 %>
		</div>
		<div class="field">
			<%= f.label :wallet_id %>
			<br>
			<%= f.number_field :wallet_id %>
		</div>

		
			<div class="actions">
				<%= f.submit %>
			</div>

		</div>

		<% end %>
	</div>

app/views/investment_funds/edit.html.erb
<h1>Editing Investment Fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment_fund %> |

<%= link_to 'Back', investment_funds_path %>

app/views/investment_funds/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Listing Investment Funds</h1>

<div row>
	<table>
		<thead>
			<tr>
				<th>Nome</th>
				<th>Data de Compra</th>
				<th>Taxa Adm</th>
				<th>Gross Profit</th>
				<th>Liquid Profit</th>
				<th>Observações</th>
				<th>Inicío do Fundo</th>
				<th>Valor da Cota</th>
				<th>Capital Investido</th>
				<th>Carteira</th>
				<th>Valor de fechamento</th>
				<th>Data do fechamento</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @investment_funds.each do |investment_fund| %>
			<tr>
				<td><%= investment_fund.name %></td>
				<td><%= investment_fund.buyDate %></td>
				<td><%= investment_fund.admTax %></td>
				<td><%= investment_fund.gross_profit %></td>
				<td><%= investment_fund.liquid_profit %></td>
				<td><%= investment_fund.aditionalInfo %></td>
				<td><%= investment_fund.fundBegin %></td>
				<td><%= investment_fund.shareValue %></td>
				<td><%= investment_fund.capital %></td>
				<td><%= investment_fund.wallet.name %></td>
				<td><%= investment_fund.closing_price %></td>
				<td><%= investment_fund.closing_date %></td>

				<td><%= link_to 'Show', investment_fund %></td>
				<td><%= link_to 'Edit', edit_investment_fund_path(investment_fund) %></td>
				<td><%= link_to 'Destroy', investment_fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>
	<%= link_to 'New Investment fund', new_investment_fund_path, class: 'button success radius small' %>
	

app/views/investment_funds/new.html.erb
<h1>New Investment Fund</h1>

<%= render 'form' %>

<%= link_to 'Back', investment_funds_path %>

app/views/investment_funds/show.html.erb
 
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @investment_fund.name %>
</p>

<p>
  <strong>Data da Compra:</strong>
  <%= @investment_fund.buyDate %>
</p>

<p>
  <strong>Taxa Adm:</strong>
  <%= @investment_fund.admTax %>
</p>

<p>
  <strong>Observações:</strong>
  <%= @investment_fund.aditionalInfo %>
</p>

<p>
  <strong>Taxa de Saída:</strong>
  <%= @investment_fund.exitTax %>
</p>

<p>
  <strong>Início do Fundo:</strong>
  <%= @investment_fund.fundBegin %>
</p>

<p>
  <strong>Gestor:</strong>
  <%= @investment_fund.manager %>
</p>

<p>
  <strong>Contado do Getor:</strong>
  <%= @investment_fund.managerContact %>
</p>

<p>
  <strong>Valor da Cota:</strong>
  <%= @investment_fund.shareValue %>
</p>

<p>
  <strong>Capital Investido:</strong>
  <%= @investment_fund.capital %>
</p>

<p>
  <strong>Carteira:</strong>
  <%= @investment_fund.wallet %>
</p>

<p>
  <strong>Closing price:</strong>
  <%= @investment_fund.closing_price %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @investment_fund.closing_date %>
</p>


<%= link_to 'Edit', edit_investment_fund_path(@investment_fund),  class: 'button info tiny' %> |
<%= link_to 'Back', investment_funds_path,  class: 'button info tiny' %>