config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  
  resources :exchanges do
    member do
      get :exchanges_movimentation
    end

    collection do
      get :exchanges_list
    end
  end

  resources :investment_funds

 resources :stocks do 
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :wallets
  

  root :to => 'home#index'  #RAILS 3

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
	belongs_to :wallet

	
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]
  helper_method :discount, :convert, :convert_current_income

  # GET /exchanges
  def index
    @exchanges = Exchange.all
  end

  # GET /exchanges/1
  def show
  end

  def convert

    if @exchange[:exchange_type] == "Dolar"
      dollar_quotation = @exchange[:initial_dollar_quotation]
      initial_income = @exchange[:initial_income] 
      reais = dollar_quotation*initial_income
    elsif @exchange[:exchange_type] == "Euro"
      euro_quotation = @exchange[:initial_euro_quotation]
      initial_income = @exchange[:initial_income]
      reais = euro_quotation*initial_income
    end

    return reais

  end

  def convert_current_income
    json_request
    if @exchange[:exchange_type] == "Dolar"
      dollar_quotation = @exchange[:dollar_quotation]
      initial_income = @exchange[:initial_income] 
      reais = dollar_quotation*initial_income
    elsif @exchange[:exchange_type] == "Euro"
      euro_quotation = @exchange[:euro_quotation]
      initial_income = @exchange[:initial_income]
      reais = euro_quotation*initial_income
    end
    reais = reais - discount
    return reais

    
  
  end

  def discount
    iof_tax = 0.38
    initial_income = @exchange[:initial_income]
    discount = (iof_tax/100)*initial_income
    return discount
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
    json_request
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  def create
    @exchange = Exchange.new(exchange_params)

    if @exchange.save
      redirect_to @exchange, notice: 'Exchange was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /exchanges/1
  def update
    if @exchange.update(exchange_params)
      redirect_to @exchange, notice: 'Exchange was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /exchanges/1
  def destroy
    @exchange.destroy
    redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.'
  end

  def json_request
      uri = URI.parse("http://developers.agenciaideias.com.br/cotacoes/json")
 
      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)
 
      response = http.request(request)
 
      if response.code == "200"
        result = JSON.parse(response.body)
        @exchange.update_attributes(:dollar_quotation => result["dolar"]["cotacao"])
        @exchange.update_attributes(:euro_quotation => result["euro"]["cotacao"])
        @exchange.update_attributes(:variation_dollar => result["dolar"]["variacao"]) 
        @exchange.update_attributes(:variation_euro => result["euro"]["variacao"]) 

        @exchange.update_attributes(:initial_dollar_quotation => @exchange[:dollar_quotation])
        @exchange.update_attributes(:initial_euro_quotation => @exchange[:euro_quotation])


      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exchange_params
      params.require(:exchange).permit(:exchange_type, :initial_income,:Wallet_id,:dollar_quotation)
    end




end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% @exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
   <b> <%= f.label "Quotation buy values in Real" %></b><br>
    <%= f.label :dollar_quotation,"Dolar:  #{@exchange[:dollar_quotation]} Variation:  #{@exchange[:variation_dollar]}" %><br>
    <%= f.label :euro_quotation,"Euro:  #{@exchange[:euro_quotation]} Variation:  #{@exchange[:variation_euro]}" %><br><br>

  <div class="field">
    <b><%= f.label :exchange_type, "Choose the exchange type." %></b><br>
    <%= f.select :exchange_type, ['Dolar', 'Euro'] %>
  </div>


  <div class="field">
    <%= f.label :initial_income, "Currency value to buy:" %><br>
    <%= f.text_field :initial_income %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>Exchange type</th>
      <th>Inicial exchange investment</th>
      <th>Buy date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.exchange_type %></td>
        <td><%= exchange.initial_income %></td>
        <td><%= exchange.created_at %></td>
        <td><%= link_to 'Show', exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path, class: 'button success radius small' %>

app/views/exchanges/new.html.erb
<h1>New Exchange</h1>

<%= render 'form' %>

<%= link_to 'Back', exchanges_path %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exchange type:</strong>
  <%= @exchange.exchange_type %>
</p>

<p>
  <strong>Inicial exchange investment:</strong>
  <%= @exchange.initial_income %>
</p>

<p>
  <strong>Buy date:</strong>
  <%= @exchange.created_at %>
</p>

<p>
  <strong>Inicial gross value in Reais:</strong>
  <%= convert %>
</p>

<p>
  <strong>Discount:</strong>
  <%= discount %>
</p>


<p>
  <strong>Current liquid value in Reais:</strong>
  <%= convert_current_income %>
</p>




<%= link_to 'Edit', edit_exchange_path(@exchange),  class: 'button info tiny' %> |
<%= link_to 'Back', exchanges_path,  class: 'button info tiny' %>