config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  
  resources :exchanges do
    member do
      get :exchanges_movimentation
    end

    collection do
      get :exchanges_list
    end
  end

  resources :investment_funds

 resources :stocks do 
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :wallets
  

  root :to => 'home#index'  #RAILS 3

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :Wallet

	def gross_income
   
	    initial = self[:initial_income] 
	    current = self[:current_income] 
	    
	    return (current - initial) * self[:amount]  
  end

    def brokerage
    initial = self[:initial_income] * self[:amount]
    
    brokerage_tax_low = 0.0025
    brokerage_tax_high = 0.0020

    if initial > 0.01 and initial < 50000
      brokerage = initial * brokerage_tax_low
      return brokerage
    elsif initial > 50000
      brokerage = initial * brokerage_tax_high
      return brokerage
    end
  end

  def  emoluments
     initial = self[:initial_income] * self[:amount]
     
     emoluments_tax = 0.000325

    return (initial)*emoluments_tax
  end

  def custody
      current = self[:current_income] * self[:amount]
      
      free = 0

      custody_tax_low = 0.000132
      custody_tax_high = 0.000076

      if current > 0.01 and current < 300000 # menor que 300 mil insento
        return free
      elsif current > 300000 and current < 1000000 # entre 300 mil e 1 milhão 
        return current * custody_tax_low
      elsif current > 1000000 and 10000000 # entre 1 milhão e 10 milhão
        return current * custody_tax_high
      end 
  end
      
  def income_tax 

    current = self[:current_income] * self[:amount]
    
    liquid_income = gross_income - (custody + emoluments + brokerage) 
    
    free = 0
    total_sale = self[:current_income] * self[:amount]
    income_tax = 0.15

    if total_sale > 20000
      return liquid_income * income_tax
    else
      return free
    end
  end

  def liquid_income

    return liquid_income = gross_income - (income_tax + custody + emoluments + brokerage )
  end

  def total_liquid_income
    all_liquid_income
    stocks = Stocks.all
    stocks.each do |stock|
      all_liquid_income =+ stock.liquid_income
    end
    return all_liquid_income 
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include StocksHelper
  
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
 
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  def show
      @stock = Stock.find(params[:id])
  end

  #GET /stocks/
  def stocks_list
    @stocks = Stock.all
  end

  def stocks_movimentation
    @stock2 = Stock.find(params[:id])
  end
  

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to @stock, notice: 'Stock was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stocks/1
  def update
    if @stock.update(stock_params)
      redirect_to @stock, notice: 'Stock was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stocks/1
  def destroy
    @stock.destroy
    redirect_to stocks_url, notice: 'Stock was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stock_params
      params.require(:stock).permit(:name, :initial_income, :current_income, :buy_date, :buy_tax, :amount, :Wallet_id, :closing_price, :closing_date)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
  
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :initial_income %><br>
    <%= f.number_field :initial_income, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :current_income %><br>
    <%= f.number_field :current_income, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :buy_date %><br>
    <%= f.datetime_select :buy_date %>
  </div>
  <div class="field">
    <%= f.label :buy_tax %><br>
    <%= f.number_field :buy_tax, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :Wallet_id %><br>
    <%= f.number_field :Wallet_id %>
  </div>
  <div class="field">
    <%= f.label :closing_price %><br>
    <%= f.number_field :closing_price, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :closing_date %><br>
    <%= f.date_select :closing_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initial Income</th>
      <th>Current Income</th>
      <th>Buy date</th>
      <th>Buy tax</th>
      <th>Amount</th>
      <th>Wallet</th>
      <th>Closing price</th>
      <th>Closing date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.initial_income %></td>
        <td><%= stock.current_income %></td>
        <td><%= stock.buy_date %></td>
        <td><%= stock.buy_tax %></td>
        <td><%= stock.amount %></td>
        <td><%= stock.Wallet.name %></td>
        <td><%= stock.closing_price %></td>
        <td><%= stock.closing_date %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: 'button success radius small'%>

app/views/stocks/new.html.erb
<div class="row">
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>
</div>

app/views/stocks/show.html.erb
<div class="row" > 
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Initial Income:</strong>
  <%= @stock.initial_income %>
</p>

<p>
  <strong>Current Income</strong>
  <%= @stock.current_income %>
</p>

<p>
  <strong>Buy date:</strong>
  <%= @stock.buy_date %>
</p>

<p>
  <strong>Buy tax:</strong>
  <%= @stock.buy_tax %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @stock.amount %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @stock.Wallet.name %>
</p>

<p>
  <strong>Closing price:</strong>
  <%= @stock.closing_price %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @stock.closing_date %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock), class: 'button info tiny' %> |
<%= link_to 'Back', stocks_path, class: 'button info tiny' %>

<br>
<p>
<strong>See the moviment of your Stock here ! </strong>
</p>
<%= link_to 'Moviment', stocks_movimentation_stock_path(@stock), class: 'button success small'   %>

app/views/stocks/stocks_list.html.erb
<p id="notice"><%= notice %></p>
<div class="row" > 
<h1>Stocks Movimentation</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initial Income</th>
      <th>Current Income</th>
      <th>Amount</th>
      <th>Gross Income</th>
      <th>Liquid Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.initial_income %></td>
        <td><%= stock.current_income %></td>
        <td><%= stock.amount %></td>
        <td><%= stock.gross_income %></td>
        <td><%= stock.liquid_income %></td> 
      </tr>
    <% end %>
     
  </tbody>
</table>

<br>

app/views/stocks/stocks_movimentation.html.erb
<p id="notice"><%= notice %></p>
<div class="row" > 

<h1> <%= @stock2.name%> Movimentation</h1>

<p>
 <strong>Gross Income:</strong>
 <%= @stock2.gross_income.round(2) %>  R$ 
</p>

<p>
  <strong>Liquid Income:</strong>
 <%= @stock2.liquid_income.round(2) %> R$
</p>

<table>
  <thead>
    <tr>
      <th>Brokerage</th>
      <th>Emoluments</th>
      <th>Custody</th>
      <th>Income Tax</th>
    </tr>
  </thead>  
  <tbody>
      <tr>
        <td><%= @stock2.brokerage.round(2)  %> R$</td>
        <td><%= @stock2.emoluments.round(2) %> R$</td>
        <td><%= @stock2.custody.round(2)  %> R$</td>
        <td><%= @stock2.income_tax.round(2) %> R$</td>
      </tr>     
  </tbody>
</table>