config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  
  resources :exchanges do
    member do
      get :exchanges_movimentation
    end

    collection do
      get :exchanges_list
    end
  end

  resources :investment_funds

 resources :stocks do 
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :wallets
  

  root :to => 'home#index'  #RAILS 3

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  belongs_to :user
  has_many :stocks
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  include StocksHelper
  include WalletsHelper
  before_action :set_wallet, only: [:show, :edit, :update, :destroy]

  helper_method :show_moving_stock

  # GET /wallets
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1
  def show
    get_variable
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  def show_moving_stock

    @stock = Stock.new
    @stock = liquid_income

  end

  # POST /wallets
  def create
    @wallet = Wallet.new(wallet_params)

    if @wallet.save
      redirect_to @wallet, notice: 'Wallet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wallets/1
  def update
    if @wallet.update(wallet_params)
      redirect_to @wallet, notice: 'Wallet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wallets/1
  def destroy
    @wallet.destroy
    redirect_to wallets_url, notice: 'Wallet was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wallet
    @wallet = Wallet.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def wallet_params
    params.require(:wallet).permit(:name, :description, :user_id)
  end
  
  def get_variable
  end

end

app/helpers/wallets_helper.rb
module WalletsHelper
	include StocksHelper
end

app/views/wallets/_form.html.erb
<%= form_for(@wallet) do |f| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% @wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form' %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<div class="row" > 
<p id="notice"><%= notice %></p>

<h1>Listing Wallets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% @wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.name %></td>
        <td><%= wallet.description %></td>
        <td><%= wallet.user.email %></td>
        <td><%= link_to 'Show', wallet %></td>
        <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
        <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet', new_wallet_path, class: 'button success radius small' %>
</div>

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form' %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<div class="row" > 
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wallet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wallet.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @wallet.user.email %>
</p>


<%= link_to 'Edit', edit_wallet_path(@wallet), class: 'button info tiny' %> |
<%= link_to 'Back', wallets_path, class: 'button info tiny' %>

<br>

<p>
	 <strong>Create, edit and follow all your assets here</strong>
</p>	
<%= link_to 'Your Exchanges', exchanges_path,  class: 'button alert radius small' %>
<%= link_to 'Your Investment Funds', investment_funds_path,  class: 'button alert radius small'%>
<%= link_to 'Your Stocks', stocks_path,  class: 'button alert radius small' %>

<br>
 <strong>You can see whats is going with your assets here !</strong>
<p>
</p>
<%= link_to  'Stock Movement', stocks_list_stocks_path, class: 'button success radius small' %>